server:
  port: ${PORT:${SERVER_PORT:8080}}
spring:
  application:
    name: online-service
  devtools:
    add-properties: false
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: greenfarm-development

logging:
  level:
    web: DEBUG
    root: INFO

---
spring:
  config:
    activate:
      on-profile: tripolymer-development
  datasource:
    url: jdbc:mysql://localhost:3306/tri_polymer_online
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: greenfarm-development
  datasource:
    url: jdbc:mysql://localhost:3306/green_farm_online
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
